### ISSUE TITLE
dtc invalid option -- '@'

### ISSUE THREAD

**Issue by zizimumu** [linux4sam/dt-overlay-at91#1]
dtc show "invalid option -- '@'".
1. build command
make KERNEL_DIR=/home/emy/microchip/linux-at91 sama5d2_xplained_dtbos

2. here is the log :
-----------------------------
cc -E -nostdinc -I/home/emy/microchip/linux-at91/include -I/home/emy/microchip/linux-at91/arch/arm/boot/dts -x assembler-with-cpp -undef -o sama5d2_xplained/sama5d2_xplained_pda7.pre.dtso sama5d2_xplained/sama5d2_xplained_pda7.dtso
/home/emy/microchip/linux-at91/scripts/dtc/dtc -@ -Wno-unit_address_vs_reg -Wno-graph_child_address -Wno-pwms_property -I dts -O dtb -o sama5d2_xplained/sama5d2_xplained_pda7.dtbo sama5d2_xplained/sama5d2_xplained_pda7.pre.dtso
/home/emy/microchip/linux-at91/scripts/dtc/dtc: invalid option -- '@'
Usage: dtc [options] <input file>
-------------------------------------

**Comment by ldesroches** [comment]
You are probably using a version of the DTC which is too old. Try to update it. I am not sure about the minimal version needed, 1.4.3 maybe. Or use the DTC within the linux-at91 kernel.
