### ISSUE TITLE
Ethernet pin configuration

### ISSUE THREAD

**Issue by charishmacherry** [linux4sam/dt-overlay-at91#6]
Hi,

Can you please help me with the ethernet pin configuration for sama5d2_xplained board as I am changing the ethernet pin from PB14 to PC10 similarly all the rx pins also1 changing. Can you help me with creating a dt-overlay file.

**Comment by noglitch** [comment]
Hi,
Sorry but this project is not meant to serve as support channel for changes in pin configuration. Please contact your Microchip representative or open a (free) support case on the Microchip website.
Thanks for your understanding. Best regards,
  Nicolas
