### ISSUE TITLE
No Such file or directory error

### ISSUE THREAD

**Issue by charishmacherry** [linux4sam/dt-overlay-at91#7]
Hi Team,
I am getting no such file or directory error when I am doing the make
**Command**: make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-gcc KERNEL_DIR=/media/charishma/b9f93c7d-ea6d-4735-b6b9-388ddc6d4942/DisplayBuild/linux-at91 sama5d2_xplained_dtbos

**Log:**
cc -E -nostdinc -I/media/charishma/b9f93c7d-ea6d-4735-b6b9-388ddc6d4942/DisplayBuild/linux-at91/include -I/media/charishma/b9f93c7d-ea6d-4735-b6b9-388ddc6d4942/DisplayBuild/linux-at91/arch/arm/boot/dts -I/media/charishma/b9f93c7d-ea6d-4735-b6b9-388ddc6d4942/DisplayBuild/linux-at91/arch/arm/boot/dts/microchip -Iinclude -x assembler-with-cpp -undef -o sama5d2_xplained/sama5d2_xplained_flx0_i2c.pre.dtso sama5d2_xplained/sama5d2_xplained_flx0_i2c.dtso
../linux-at91/scripts/dtc/dtc -@ -Wno-unit_address_vs_reg -Wno-graph_child_address -Wno-pwms_property -I dts -O dtb -o sama5d2_xplained/sama5d2_xplained_flx0_i2c.dtbo sama5d2_xplained/sama5d2_xplained_flx0_i2c.pre.dtso
make: ../linux-at91/scripts/dtc/dtc: No such file or directory
make: *** [Makefile:37: sama5d2_xplained/sama5d2_xplained_flx0_i2c.dtbo] Error 127
rm sama5d2_xplained/sama5d2_xplained_flx0_i2c.pre.dtso

**Comment by cristibirsan** [comment]
Hi, the latest commit from dt overlay repository compiles fine.
For overlay use: https://github.com/linux4microchip/dt-overlay-mchp, branch main.
For kernel use https://github.com/linux4microchip/linux, branch: linux-6.1-mchp. Make sure you compile the kernel first. It seems your dtc is missing.

**Comment by charishmacherry** [comment]
Hi,
Issue is resolved.
Thank you

**Comment by charishmacherry** [comment]
Resolved the issue 
Thank you
